---

- name: Learn Handlers
  hosts: webserver
  gather_facts: no
  tasks:
    - name: Print a message
      debug:
        msg: 'I executed normally'
      #changed_when: true
      notify:
        - Handler 1
        - Handler 2
    
    #- meta: flush_handlers

    - name: Task 003
      command: "echo 'Task 003'"
      when: "'003' in inventory_hostname"
      notify: Handler 3

    - name: Ping hosts
      ping:

  handlers:
    - name: Handler 1
      debug:
        msg: "Handler 1"
    
    - name: Handler 2
      debug:
        msg: "Handler 2"

    - name: Handler 3
      debug:
        msg: "Handler 3"

    - name: Handler 4
      debug:
        msg: "Handler 4"
      listen: Handler 2