- name: Using vaults
  hosts: rocky
  gather_facts: no
  tasks:
    - name: Copy encrypted file
      copy:
        src: confidential_data.txt
        dest: /tmp/confidential_data.txt

    - name: Display file contents
      command: cat /tmp/confidential_data.txt
      register: command_output

    - name: Print to console
      debug:
        msg: "{{command_output.stdout}}"


